smoke:
	poetry run \
	python main.py \
	--tag smoke \
	--host_port localhost:4444 \
	--thread 20 \
	--env staging \
	--data_env staging \
	--qase true \
	--rerun true

smoke2:
	poetry run \
	python main.py \
	--tag smoke2 \
	--host_port localhost:4444 \
	--thread 20 \
	--env staging \
	--data_env staging \
	--qase true \
	--rerun true